CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(100) NOT NULL,
                                     email VARCHAR(100) NOT NULL,
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(100) NOT NULL,
                                     CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     annotation VARCHAR(2000) NOT NULL,
                                     category BIGINT NOT NULL,
                                     confirmed_requests BIGINT,
                                     created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     description VARCHAR(7000) NOT NULL,
                                     event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     initiator BIGINT NOT NULL,
                                     lat FLOAT NOT NULL,
                                     lon FLOAT NOT NULL,
                                     paid BOOLEAN,
                                     participant_limit BIGINT,
                                     published_on TIMESTAMP WITHOUT TIME ZONE,
                                     request_moderation BOOLEAN,
                                     state VARCHAR NOT NULL,
                                     title VARCHAR(120) NOT NULL,
                                     views BIGINT,
                                     rating_visibility BOOLEAN,
                                     FOREIGN KEY (category) REFERENCES categories (id),
                                     FOREIGN KEY (initiator) REFERENCES users (id) ON DELETE CASCADE,
                                     CONSTRAINT PK_EVENT PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     pinned BOOLEAN NOT NULL,
                                     title VARCHAR NOT NULL,
                                     CONSTRAINT UQ_TITLE UNIQUE (title),
                                     CONSTRAINT PK_COMPILATION PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     event BIGINT NOT NULL,
                                     requester BIGINT NOT NULL,
                                     status VARCHAR NOT NULL,
                                     FOREIGN KEY (event) REFERENCES events(id),
                                     FOREIGN KEY (requester) REFERENCES users (id) ON DELETE CASCADE,
                                     CONSTRAINT UQ_REQUEST UNIQUE (event, requester),
                                     CONSTRAINT PK_REQUEST PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations_events (
                                     compilation_id BIGINT NOT NULL,
                                     event_id BIGINT NOT NULL,
                                     PRIMARY KEY (compilation_id, event_id),
                                     FOREIGN KEY (compilation_id) references compilations(id) ON DELETE CASCADE,
                                     FOREIGN KEY (event_id) references events(id) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS likes (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     liker BIGINT NOT NULL,
                                     type BOOLEAN NOT NULL,
                                     timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     CONSTRAINT PK_LIKE PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users_likes (
                                     user_id BIGINT NOT NULL,
                                     like_id BIGINT NOT NULL,
                                     PRIMARY KEY (user_id, like_id),
                                     FOREIGN KEY (user_id) references users(id) ON DELETE CASCADE,
                                     FOREIGN KEY (like_id) references likes(id) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS events_likes (
                                     event_id BIGINT NOT NULL,
                                     like_id BIGINT NOT NULL,
                                     PRIMARY KEY (event_id, like_id),
                                     FOREIGN KEY (event_id) references events(id) ON DELETE CASCADE,
                                     FOREIGN KEY (like_id) references likes(id) ON DELETE CASCADE

);



