CREATE TABLE IF NOT EXISTS apps (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(100) NOT NULL,
                                     uri VARCHAR NOT NULL,
                                     CONSTRAINT UQ_USER_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS hits (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    app VARCHAR(100) NOT NULL,
                                    uri VARCHAR NOT NULL,
                                    ip VARCHAR NOT NULL,
                                    timestamp TIMESTAMP NOT NULL,
                                    app_id BIGINT NOT NULL,
                                    FOREIGN KEY (app_id) REFERENCES apps(id)
);